Repository BiggerThanOurselves/anonymousCents, pull requests merged in 2020-10, with the labels that each got.

#7 Refatoracao/menu
  .gitignore
  __main__.py
  main.py
  src/data/constantes.py
  src/data/credentials.json
  src/scripts/__init__.py
  src/scripts/inicia_sistema.py
Labels: enhancement

#9 Criação de método principal para criação das planilhas
  .gitignore
  __init__.py
  __main__.py
  requirements.txt
  src/scripts/cria_planilhas.py
  src/scripts/inicia_sistema.py
  src/scripts/sheets.py
Labels: enhancement

#10 adiciona open_json
  src/scripts/envia_email.py
  src/scripts/inicia_sistema.py
Labels: enhancement

#12 Refatoracao/modularizacao scripts
  __main__.py
  src/scripts/__init__.py
  src/scripts/cria_planilhas.py
  src/scripts/envia_email.py
  src/scripts/inicia_sistema.py
  src/scripts/util/__init__.py
  src/scripts/util/dicionario_apelidos.py
  src/scripts/util/envia_email.py
  src/scripts/util/manipular_json.py
  src/scripts/util/verificadores.py
Labels: Refatoração

#13 BugFix: Vetorizadores
  src/scripts/util/dicionario_apelidos.py
  src/scripts/util/envia_email.py
  src/scripts/util/verificadores.py
Labels: Refatoração

#14 Adiciona método de cadastro de e-mail único
  __main__.py
  src/scripts/__init__.py
  src/scripts/cadastra_email.py
  src/scripts/inicia_sistema.py
  src/scripts/util/__init__.py
  src/scripts/util/dicionario_apelidos.py
  src/scripts/util/envia_email.py
  src/scripts/util/manipula_planilhas.py
  src/scripts/util/manipular_json.py
Labels: enhancement

#15 adiciona envia_email para unica pessoa e deleta dados da planilha
  src/scripts/cadastra_email.py
  src/scripts/inicia_sistema.py
  src/scripts/util/envia_email.py
  src/scripts/util/manipula_planilhas.py
Labels: enhancement

#16 Refatoração e adição de permissões para os e-mails cadastrados
  __main__.py
  src/scripts/inicia_sistema.py
  src/scripts/util/dicionario_apelidos.py
  src/scripts/util/envia_email.py
  src/scripts/util/manipula_planilhas.py
  src/scripts/util/verificadores.py
Labels: enhancement

#18 BugFix ao iniciar o sistema
  .gitignore
  __main__.py
  src/data/.gitignore
  src/data/emails.txt
  src/scripts/inicia_sistema.py
  src/scripts/util/__init__.py
  src/scripts/util/manipula_planilhas.py
Labels: Refactoring

#19 Refatoracao/inicia sistema
  src/scripts/cadastra_email.py
  src/scripts/util/manipula_planilhas.py
  src/scripts/util/verificadores.py
Labels: Refactoring

#20 adiciona refatoração do README e corrige frase
  README.md
  src/scripts/util/verificadores.py
Labels: documentation

#21 Refatoraçoes basicas para nao deixar o codigo
  src/scripts/util/envia_email.py
  src/scripts/util/manipula_planilhas.py
  src/scripts/util/verificadores.py
Labels: Refactoring
